### ISSUE TITLE
Add funding info to AFP forms, when available

### ISSUE THREAD

**Issue by draciti** [WormBase/ACKnowledge#225]

**Comment by valearna** [comment]
Create 'about' widget. @vanaukenk and @draciti will add content for the about page, including funding info

**Comment by draciti** [comment]
@valearna this is the draft for the about widget. Feel free to edit as you see fit.
https://docs.google.com/document/d/1jrCBBJIpsx8E423hu60jypGCv7Y0zicCeDBTsBt3mn0/edit

Please use the same text on the following pages as well -(will replace the current paragraphs 'WormBase ACKnowledge):

- [ ] https://wormbase.github.io/ACKnowledge/
- [ ] https://github.com/WormBase/ACKnowledge

**Comment by draciti** [comment]
In the GitHub page -https://github.com/WormBase/ACKnowledge- change the title from 'ACKnowledge' to 'Author Curation to Knowledgebase' and add the square logo before the title

**Comment by valearna** [comment]
Ready to test

New About page in the submission form: http://textpressocentral.org:3000/about?paper=00062469&passwd=1646266062.3484852&title=Influences%20of%20HLH-2%20stability%20on%20anchor%20cell%20fate%20specification%20during%20Caenorhabditis%20elegans%20gonadogenesis.&journal=G3%20%28Bethesda%29&pmid=35134193&doi=10.1093/g3journal/jkac028&personid=220&hide_genes=false&hide_alleles=false&hide_strains=false

Website with new description taken from the about page: https://wormbase.github.io/ACKnowledge/

Github repo with new readme: https://github.com/WormBase/ACKnowledge/tree/develop

**Comment by draciti** [comment]
looks good, closing
