### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by draciti** [WormBase/ACKnowledge#226]
Change AFP tp ACKnowledge all over

**Comment by valearna** [comment]
Make sure we replace AFP in the FAQs and release notes

**Comment by valearna** [comment]
@draciti do you remember how we created the email address no-reply.afp@wormbase.org and help.afp@wormbase.org? Can you create no-reply.acknowledge@wormbase.org and help.acknowledge@wormbase.org?

**Comment by valearna** [comment]
If we rename the project also in the readme and release notes, should we say "ACKnowledge (previously known as Author FIrst Pass - AFP)"?

**Comment by vanaukenk** [comment]
- [ ] Update Submit Data entry on WB
- [ ] WB model changes?
- [ ] Update WB display on Person and Paper pages

**Comment by valearna** [comment]
Any update on the new email addresses @draciti @vanaukenk?

**Comment by draciti** [comment]
@valearna I will check in with Todd

**Comment by draciti** [comment]
Wrote to Todd on 06-09-2022:
Hi Todd, 

If I am not mistaken, you helped us create the following email addresses: no-reply.afp@wormbase.org and help.afp@wormbase.org.
Can you please change them to: no-reply.acknowledge@wormbase.org and help.acknowledge@wormbase.org?

**Comment by valearna** [comment]
Todd implemented the email group changes
