### ISSUE TITLE
Save genes and species to pap_genes and pap_species when author saves overview page after full submission

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#227]
Currently, pap_genes and pap_species are populated/updated only when a full submission is finalized by clicking the "finish and submit" button. Authors may update gene and species lists after they finish the submission and the pap_ tables should be updated even if they click the widget specific "save and continue" button.

**Comment by draciti** [comment]
Tested on genes and species.
Worked for genes but not for species. 
@valearna to take a look

**Comment by draciti** [comment]
Tested together on 08-08. Working fine. Closing
