### ISSUE TITLE
Send out reminder emails every two weeks?

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#234]
We could get more submissions with more frequent reminders

**Comment by draciti** [comment]
let's try it!

**Comment by valearna** [comment]
live on the prod pipeline, the script will start next week and will send out reminders every 2 weeks for 2 months

**Comment by draciti** [comment]
thanks @valearna , anything we should test here or good to close?

**Comment by valearna** [comment]
Let's keep it open for the first rounds of reminders. I'll monitor the logs to make sure everything is ok

**Comment by valearna** [comment]
This looks good to me. Closing
