### ISSUE TITLE
Add author curation portal link to first contact email

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#235]

**Comment by valearna** [comment]
@vanaukenk Would something like "View all your papers already in the Acknowledge system" be ok?

**Comment by draciti** [comment]
The following sentences need a period after the links:

- If you would like to flag* your paper for detailed curation, please click [here]

- You can view all your papers already in the ACKnowledge system on the [Author Curation Portal]

Also, should we modify this sentence:
*Flagging your paper involves identifying the types of data present and should take <20 minutes.

to:
*Flagging your paper involves validating automatically extracted entities and identifying the types of data present, and should take <20 minutes.

**Comment by valearna** [comment]
Will generate a new contact email for testing. @draciti and @vanaukenk close if everything looks ok

**Comment by draciti** [comment]
@valearna sorry if I missed this. Did you already send out the test email with the revised text?

**Comment by draciti** [comment]
modified in the code. Done, closing
