### ISSUE TITLE
Add free text box for "chemical induced phenotype" 

### ISSUE THREAD

**Issue by draciti** [WormBase/ACKnowledge#236]
From Author's feedback in the AFP comments section:
00060933: Hello, I checked "chemical induced phenotype" but I can't find any space to describe it.

We should  discuss if we want to implement a free text box for "chemical induced phenotype". if so, we should do the same for "Environmental Induced Phenotype".

**Comment by valearna** [comment]
We decided to add the text box

**Comment by valearna** [comment]
We want include this in 4.0 If time permits, but it has lower priority than other tasks

**Comment by valearna** [comment]
Ready to test on dev @draciti @vanaukenk

**Comment by draciti** [comment]
Tested for 00059841.
All good. Also checked on the curation status form on mangolassi that the free text is properly saved.
Closing
