### ISSUE TITLE
Replace 'SVM' on dashboard with 'NN' wherever appropriate

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/ACKnowledge#237]
Just finished presenting to the Alliance literature working group and realized we hadn't put this change into production, yet.

**Comment by valearna** [comment]
Still need to modify dashboard 'filters and options' in paper lists

**Comment by vanaukenk** [comment]
It looks like the 'filters and options' has also been updated from SVM -> NN.

All looks good.
