### ISSUE TITLE
Improve the comments section

### ISSUE THREAD

**Issue by draciti** [WormBase/ACKnowledge#238]
1. In the 'comments' box add placeholder text highlighting what type of feedback we are after: e.g. Please let us know how we can make the submission easier for you
2. Add checkboxes below the 'comments' box
    - Did filling out the form identified any needed corrections in the paper? e.g. typos in alleles, strains (yes/no)

**Comment by valearna** [comment]
We need more requirements for point 2. of this ticket. Each checkbox will need a new table in postgres and we need to define the list of checkboxes to add.

**Comment by valearna** [comment]
The first part is ready to test on dev. I'm moving the second part to a new ticket.

**Comment by vanaukenk** [comment]
After a few months, I'm looking at this with new eyes and thinking we could rename the field on the form to something like 'Please give us your feedback' and add more suggested feedback text:

Please let us know about your experience with this submission. What did you like? What can we do to make the process easier? Did we miss anything?

Or something along those lines.....

**Comment by valearna** [comment]
I modified the form following @vanaukenk's comments. Can you take a look and close this ticket if everything looks good @vanaukenk @draciti ?

**Comment by draciti** [comment]
@valearna looks good to me. @vanaukenk, if you  are happy feel free to close

**Comment by vanaukenk** [comment]
Looks great.  Thanks @valearna
