### ISSUE TITLE
Change column "Author changed" in dashboard

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#240]
Use N/A instead of No when there is no submission by author. Use N/A instead of null also for the "Submitted/confirmed by author" column

**Comment by draciti** [comment]
Tested this paper 00061894 and looks good. Leaving open to give @vanaukenk a chance to test

**Comment by vanaukenk** [comment]
I also checked the above, 00061894, as well as 00061898 (not submitted by the author) and the changes looks fine.
