### ISSUE TITLE
Update author portal page to remove 'corresponding'

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#245]
We should update the first sentence on this page:  https://mypapers.afp.textpressolab.com/ to remove 'corresponding'

**Comment by valearna** [comment]
Ready to test on new dev author portal: http://textpressocentral.org:3002/

**Comment by vanaukenk** [comment]
I reviewed the text on this page and also tested with my email address and all looks fine.  
@valearna shall we close this ticket?
