### ISSUE TITLE
Finalize design and implement an ACKnowledge logo

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/ACKnowledge#248]

**Comment by draciti** [comment]
<img width="755" alt="Screen Shot 2022-03-28 at 4 18 07 PM" src="https://user-images.githubusercontent.com/901243/160915073-ae22f3c2-6fee-42a4-ba6e-2b9571241534.png">

**Comment by draciti** [comment]
Adding Sam's design here for discussion
