### ISSUE TITLE
Follow up with processing of WBPaper00064064

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/ACKnowledge#252]
The first author asked via WB help to make gene/protein connections for this paper which is now added to the WB bibliography.

Note that many genes/proteins are listed only in Tables, so it'd be good to see what the ACKnowledge coverage is.

**Comment by vanaukenk** [comment]
PDF was added to tazendra on 2022-05-29

**Comment by vanaukenk** [comment]
Last neural network was run on 2022-05-23

**Comment by draciti** [comment]
Closing this. In Hinxton court
https://github.com/WormBase/website/issues/8752
