### ISSUE TITLE
Change 'AFP' -> 'ACKnowledge' in 'thanks for your submission' email

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#254]
The text for this email is defined in the API and still contains 'AFP' instead of 'ACKnowledge'. This text should be fixed and moved to the config file where all the other emails are defined.

**Comment by valearna** [comment]
I've just resubmitted data for 00059841 and you should have received an email with the text fixed. Let me know if everything looks good @draciti.

**Comment by draciti** [comment]
I propose to change the first sentence of the email as follows.

Current text:
Thank you for your participation in ACKnowledge.

Proposed text:
Thank you for your participation in the Author Curation to Knowledgebase (ACKnowledge) project, previously known as Author First Pass.

@vanaukenk feel free to fix the grammar :)

**Comment by draciti** [comment]
Received and looking good. Closing
