### ISSUE TITLE
Add Banner to github website

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#255]
Maybe remove color background and put banner at the top. We need to see how it looks. Alternatively we could change the banner color to white with transparent background

**Comment by valearna** [comment]
Web page now in html with banner and release notes

**Comment by valearna** [comment]
Added banner to github repo page: https://github.com/WormBase/ACKnowledge/tree/develop
This is the new github website: https://wormbase.github.io/ACKnowledge/

**Comment by valearna** [comment]
Would it help to have a smaller font for the "Author Curation to Knowledgebase" title? Should we ask Shannon to create a banner with a smaller font?

**Comment by draciti** [comment]
Proposed banner size mock-up
[Proposed banner look.pptx](https://github.com/WormBase/ACKnowledge/files/9309194/Proposed.banner.look.pptx)

**Comment by draciti** [comment]
Ask Shannon to reduce the font size of the banner.
Give Sarah the  heads up for payment

**Comment by draciti** [comment]
<img width="1086" alt="Screen Shot 2022-08-19 at 11 26 30 AM" src="https://user-images.githubusercontent.com/901243/185664465-c43f4863-6fcd-483f-961b-136a5751ed4f.png">
