### ISSUE TITLE
Adding banner to submission form

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#257]

**Comment by valearna** [comment]
ready to test on dev

**Comment by draciti** [comment]
@valearna looks good.
I would make it a bit smaller. @vanaukenk ?
Adding a link here for easier testing: http://textpressocentral.org:3000/overview?paper=00059841&passwd=1600893658.7796698&title=RPamide%20neuropeptides%20NLP-22%20and%20NLP-2%20act%20through%20GnRH-like%20receptors%20to%20promote%20sleep%20and%20wakefulness%20in%20C.%20elegans.&journal=Sci%20Rep&pmid=32555288&doi=10.1038/s41598-020-66536-2&personid=11490&hide_genes=false&hide_alleles=false&hide_strains=false

**Comment by valearna** [comment]
![image](https://user-images.githubusercontent.com/26348851/183688923-4bbac5d3-a755-43be-8588-4896ded29f55.png)

**Comment by draciti** [comment]
ok. Adding here the screenshot of the big one for comparison.

<img width="1031" alt="Screen Shot 2022-08-09 at 10 53 59 AM" src="https://user-images.githubusercontent.com/901243/183753647-a478027e-c22d-4cb0-8070-936b6ff11ecf.png">

**Comment by draciti** [comment]
I still vote for a little smaller but I leave the final decision to the majority :)

**Comment by draciti** [comment]
@vanaukenk agrees to make it a bit smaller, we can  take a look on Friday Aug 12 during  the ACKnowledge meeting

**Comment by draciti** [comment]
Ask Shannon to reduce the font size of the banner.
Give Sarah the  heads up for payment
