### ISSUE TITLE
Add logo to emails

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#258]
Try both banner and logo

**Comment by valearna** [comment]
I was able to add the image but it is also displayed as an attachment and creates issues with caltech spam filters - I'm unable to send emails with images to my caltech account. I think that we should revisit the idea of adding the logo to emails.

**Comment by draciti** [comment]
Sounds good. We can discuss this tomorrow

**Comment by azurebrd** [comment]
Are you sending the emails as html with the image in an <img src=""> pointing to the URL of the image ?  I haven't used the gmail api much, so I don't know what's possible.  Previously sending through sendmail, I think one could send emails as html and then nothing would be an attachment.  I realize you wouldn't want to send through sendmail though.

**Comment by valearna** [comment]
I'm sending the email as html with the image embedded. I read the file from python and add it as a mime image. I think that the way it is displayed depends on the client and with gmail it is displayed both in the email body and as an attachment. There's also the issue that caltech servers are blocking the message, maybe temporarily but it means that there may be more rules for emails with images and I think it's more important to reach the authors and avoid spam filters than having the image in all emails but with the risk of being blocked

**Comment by azurebrd** [comment]
If it's always the same image, could just hotlink it to the URL instead of mime attaching it ?  I guess that wouldn't look good if they view the email without internet connection ?  I agree on prioritizing reaching authors, I don't have a stake on this, just wondering technical things.  Thanks.

**Comment by valearna** [comment]
Thanks @azurebrd I haven't thought of adding the image as html. It works, and in this way caltech email server is not blocking the messages!

**Comment by valearna** [comment]
I deployed the version with the logo to dev but I can switch to the banner depending on what @draciti and @vanaukenk prefer

**Comment by draciti** [comment]
Pasting the email here for discussion
<img width="1025" alt="Screen Shot 2022-08-12 at 10 00 57 AM" src="https://user-images.githubusercontent.com/901243/184383452-5f00cb9e-b29e-4ff0-9f6d-f238242b49c1.png">

**Comment by draciti** [comment]
<img width="1036" alt="Screen Shot 2022-08-12 at 10 10 24 AM" src="https://user-images.githubusercontent.com/901243/184385196-482b6341-db81-4348-ab13-e2337992b3b8.png">

**Comment by draciti** [comment]
all agree banner is better, need to replace with  a smaller one after talking to shannon
