### ISSUE TITLE
Add 'formerly known as Author First Pass' to all emails

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#259]

**Comment by draciti** [comment]
In the footer of the email right after 'ACKnowledge'

**Comment by draciti** [comment]
Add also to reminder emails and thank you emails

**Comment by valearna** [comment]
done, this is the config file with all email content: https://github.com/WormBase/ACKnowledge/blob/master/src/backend/config.yml

**Comment by draciti** [comment]
Looks good to me. Leaving open to give @vanaukenk a chance to take a look
