### ISSUE TITLE
Add funding info to all emails to authors

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#260]
Author Curation to Knowledgebase (ACKnowledge) is supported by <grant number>

**Comment by vanaukenk** [comment]
NIH #R01 LM013871-01

**Comment by valearna** [comment]
Can I add the same sentence used in the About page to the emails? "The ACKnowledge project is supported by grant RO1 OD023041 from the National Library of Medicine at the US National Institutes of Health."

**Comment by draciti** [comment]
looks good. Closing
