### ISSUE TITLE
Add a free text box for new species (or species that are not in the autocomplete).

### ISSUE THREAD

**Issue by draciti** [WormBase/ACKnowledge#261]

**Comment by valearna** [comment]
ready to test

**Comment by draciti** [comment]
Added a new species text for this paper.
http://textpressocentral.org:3000/comments?paper=00059841&passwd=1600893658.7796698&title=RPamide%20neuropeptides%20NLP-22%20and%20NLP-2%20act%20through%20GnRH-like%20receptors%20to%20promote%20sleep%20and%20wakefulness%20in%20C.%20elegans.&journal=Sci%20Rep&pmid=32555288&doi=10.1038/s41598-020-66536-2&personid=11490&hide_genes=false&hide_alleles=false&hide_strains=false

Need to check if @vanaukenk receives a notification

**Comment by draciti** [comment]
looks good closing
