### ISSUE TITLE
Release notes v 4.0

### ISSUE THREAD

**Issue by draciti** [WormBase/ACKnowledge#263]
@draciti and @vanaukenk to compile v4.0 release notes

**Comment by draciti** [comment]
Draft started here: https://docs.google.com/document/d/17dcVaBmQrO5fmBPFpfLtyrYW0Vn-th2AhEBAggCfcL8/edit#

**Comment by valearna** [comment]
I've slightly changed the wording to be consistent with older releases. I've also merged all author curation portal bullet points into one since there were a lot of repetitions. Let me know how it looks. You can check the submission form, the website or the github repo. They all have the same notes

**Comment by draciti** [comment]
Looks good to me. Adding link here for today's discussion: http://textpressocentral.org:3000/release_notes?paper=00059841&passwd=1600893658.7796698&title=RPamide%20neuropeptides%20NLP-22%20and%20NLP-2%20act%20through%20GnRH-like%20receptors%20to%20promote%20sleep%20and%20wakefulness%20in%20C.%20elegans.&journal=Sci%20Rep&pmid=32555288&doi=10.1038/s41598-020-66536-2&personid=11490&hide_genes=false&hide_alleles=false&hide_strains=false

**Comment by draciti** [comment]
Slightly changed the wording during the ACKnowledge meeting.
