### ISSUE TITLE
Review ACKnowledge FAQs

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/ACKnowledge#266]
We need to review the ACKnowledge FAQs to:

1. Add a question about the Author Curation Portal
2. Update mentions of Author First Pass -> ACKnowledge

**Comment by draciti** [comment]
@valearna updated all mentions of AFP to ACKnowledge.

Need to discuss at the next ACKnowledge meeting the question about the Author Curation Portal.
@valearna mentioned that the authors should have the link if the paper was processed

**Comment by draciti** [comment]
Add this question
Q:How can I find my other papers that are in the ACKnowledge system?
A:You can access the Author Curation Portal here <https://acp.acknowledge.textpressolab.com/> 

To add below this question:
Can I submit a paper for which I haven't received an ACKnowledge link?

**Comment by valearna** [comment]
ready to test on dev @draciti @vanaukenk

**Comment by draciti** [comment]
looks good, you can make it live. thanks @valearna . I will test again once live and will close then

**Comment by valearna** [comment]
thanks @draciti, it's live on prod now

**Comment by draciti** [comment]
tested in production. Looks good

**Comment by vanaukenk** [comment]
Daniela and Kimberly reviewed the current FAQs and here is the [doc](https://docs.google.com/document/d/18phdWEB6sdPtN8DBoG34YeQma3SGxGcizX5RoEAgTk0/edit) with recommended changes.

**Comment by draciti** [comment]
I spot checked the text and the FAQs are updated based on the latest doc. https://docs.google.com/document/d/18phdWEB6sdPtN8DBoG34YeQma3SGxGcizX5RoEAgTk0/edit
Closing
