### ISSUE TITLE
Ranjana'r request - disease (july 22nd)

### ISSUE THREAD

**Issue by draciti** [WormBase/ACKnowledge#273]
Hello Kimberly, Daniela and Valerio

I’ve been thinking about how to make it clear to the authors what exactly we mean by a disease model paper. Some authors get it but some still flag a paper for human disease model data without really understanding what it means resulting in decreased efficiency of the whole process, including a waste of the author's and curator’s time. 

On the other hand there are authors who understand exactly what we mean and have even been writing great “disease model descriptions” in the “Comments” section and I have been delighted with these and copying these verbatim into this field in the disease OA (three examples below but there are many more). So we should provide a clear field for this with examples.

Adding some new fields in the Acknowledge form UI for disease will force an author to think about whether it is a true disease model paper or not, thus reducing false positives and will also help us greatly in the curation process as we are sort of providing them space to curate their own data.

If you have space in your next ACKnowlegde group meeting please let me know, as it’s good to also talk about this, if this Monday’s agenda is full, I’d be happy to make some other Monday.

Thanks 
Ranjana

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Here are the new fields I’ve been thinking about.

Keep:  
The paper describes an experimental model for a specific human disease (e.g., Parkinson’s disease) by employing at least one of the followin:

Gene/allele or strain that recapitulates disease phenotype(s) and provides insight into disease pathogenesis. Please provide official names for strains (e.g., CL2006).
Transgenic studies with human and/or worm disease relevant gene.
Modifiers of a new or previously established disease model (e.g., drugs, herbals, chemicals, etc).


Add the following new fields:
Specific human disease you are studying <box for human disease name> . (Ideally it would be great to have the Disease Ontology available as a drop-down. But if this is too much we could just give them a free text box)
Models used (please give us the model/s used in your experiments including the the gene studied) :
Allele                      <box for allele name>
Transgene              <box for transgene name>
Strain                      <box for strain name> 
The C. elegans gene/s that above models are associated with                              <box for gene name> 
If this is a transgenic study with a human gene, please enter human gene name  <human gene name>

(My comment: Maybe we could provide drop-down lists for the authors to choose for the above genetic entities and provide boxes for those that are new, I think you already do this for other categories, so we definitely should make use of this feature here.)

Disease Model Description (write a short description of the disease model you have used, see examples below) <box for disease model description>
(my comment--maybe we can pick two of the below model descriptions that authors have provided in the comments box, I’m just so proud of these authors and couldn’t resist :), there are many more):
"UDN100161 models a variant of unknown significance identified in a proband with microcephaly, epilepsy, and developmental delay, and gives data that the variant impairs pph-5 function in neurons and in embryogenesis.”
"Mutations in human GTF2H5/TTDA lead to trichothiodystrophy disease. Our analysis of DNA repair and transcription status of the gtf-2h5 (tm6360) mutant provides insight into the etiology of trichothiodystrophy, as it highlights the nucleotide excision repair and transcription initiation defects due to GTF-2H5 dysfunction."
"wdr-60(dan1) allele recapitulates a truncating mutation observed in WDR60-associated Short rib polydactyly syndrome (SRPS) in humans.

**Comment by draciti** [comment]
discussed that having all the extra fields is a bit onerous for the author.
However, we can put an example text in the comment box.
Discuss with Ranjana about creating a disease curation form like the phenotype community curation form.

**Comment by draciti** [comment]
Discussed with Ranjana, ok to put the example in the free text box. Ranjana will provide it

**Comment by vanaukenk** [comment]
AI: double-check with Ranjana about author flagging for disease.

**Comment by rankishore** [comment]
I think we are doing quite okay with not getting too many false positives with the disease model papers coming through the Acknowledge pipeline. The explanation text that we added for what we are looking for in a disease model paper seems to be sufficient for now. So let's leave it this way unless we start getting a lot of false positives.
