### ISSUE TITLE
Error message on ACKnowledge form

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/ACKnowledge#281]
Hi @valearna @draciti 

I just tried to look at the form for a recently processed paper and got this error message:

![image](https://github.com/WormBase/ACKnowledge/assets/1730534/445b03f6-80da-4d80-a8f0-70864fad1c8f)

In the dashboard there are genes, species, etc. listed, but I don't see them on the form.

**Comment by valearna** [comment]
The form is working for me. Maybe a temporary network error on your end?

**Comment by valearna** [comment]
or maybe you need to do a hard refresh of the page?

**Comment by valearna** [comment]
I changed the form to fetch data from the dockerized system instead of tazendra but maybe you have a cached version of the form that is still trying to connect to tazendra

**Comment by vanaukenk** [comment]
Thanks for checking @valearna 
I checked the paper again and it looks okay now, and I checked another paper, too, and that one is also okay.
Maybe it was just a temporary network issue.
