### ISSUE TITLE
Paper without title

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#282]
There's at least  one paper processed by ACKnowledge that doesn't have a pap_title value in the caltech postgres db. Can you check 00065841 @vanaukenk @draciti ? This is causing the dashboard to fail when trying to retrieve the list of papers with full summission by authors

**Comment by vanaukenk** [comment]
Thanks for letting us know @valearna 
That's kind of strange - the title definitely wasn't there, but I don't see anything unusual about it that would have prevented it from being added from the PubMed XML.
I just added the title manually in the paper editor.

**Comment by draciti** [comment]
good to close?
