### ISSUE TITLE
Add a download button to the sentence level classification page in the dashboard that generates a csv file with all sentences and their classifications

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#288]
1st column contains the sentence, then 3 cols for classification values

**Comment by valearna** [comment]
Show duplicate sentences only once but add a column with the counter for validation

**Comment by valearna** [comment]
The 'download as CSV' button is ready to test on dev @draciti @vanaukenk: https://dashboard.acknowledge-dev.textpressolab.com

**Comment by draciti** [comment]
thank you @valearna !!!!
I'll test today

**Comment by valearna** [comment]
Change 'CSV' to 'TSV'
Add empty columns for validation
Add additional columns for extra validation

**Comment by vanaukenk** [comment]
Thank you @valearna 
The download worked great for my positive kinase activity paper, 00066011.
We can talk at today's ACKnowledge meeting about how we want to move forward with the analyses.
