### ISSUE TITLE
Process a zebrafish paper to test sentence extraction for gene expression

### ISSUE THREAD

**Issue by draciti** [WormBase/ACKnowledge#298]
[This paper](https://literature.alliancegenome.org/Biblio/?action=display&referenceCurie=AGRKB:101000000391780) (WBPaper00028748) in the WB corpus has Zebrafish expression data-> to test for sentence extraction -> [Valerio Arnaboldi](mailto:valerio.arnaboldi@wormbase.org), can you process it with ACKnowledge?

**Comment by valearna** [comment]
I processed the paper on prod @draciti

**Comment by draciti** [comment]
Excellent, thank you!
It works well. I am going to open a ticket for myself to evaluate the paper. Closing this one
