### ISSUE TITLE
Remove 'recently' from email for the microPubication paragraph

### ISSUE THREAD

**Issue by draciti** [WormBase/ACKnowledge#301]
@valearna can you please remove the word recently also from the microPublication bit in the email we send to authors?
Thanks!

In addition, WormBase has recently launched microPublication Biology, a peer-reviewed journal
that publishes citable, single experimental results, such as those often omitted from standard
journal articles due to space constraints or confirmatory or negative results. If you have such
unpublished data generated during this study, we encourage you to submit it [here](https://www.micropublication.org/submit-new-article/).

**Comment by vanaukenk** [comment]
This also looks good in the most recent emails.
