### ISSUE TITLE
Thank contributors at the end of the year

### ISSUE THREAD

**Issue by draciti** [WormBase/ACKnowledge#309]
Send a thank you email to authors on December 1st

- [ ] Compile a list of email address for all contributors
- [ ] Send the email with the subject line and text below

SUBJECT: WormBase is better because of you!
On behalf of WormBase and the ACKnowledge community curation project, we want to thank you for contributing your expertise to our knowledgebase by curating your papers.  By participating in the ACKnowledge community curation project, you’ve helped associate your papers with the genes, alleles, and other reagents you used in your work, and alerted us to the types of data you studied.  Your help is invaluable in getting research into WormBase in a more timely manner and we truly appreciate your efforts.
We wish you all the best for your future research endeavors and look forward to seeing your work in 2025!
If you’d like to curate more papers, please see the ACKnowledge author portal.

**Comment by draciti** [comment]
@valearna we would like to send out a thank you message to the ACKnowledge contributors. Is it going to be hard to compile a list of contributors? Thank you

**Comment by valearna** [comment]
It should be easy to get the list. Do you need all contributors who ever submitted data or just the ones who submitted this year?

**Comment by valearna** [comment]
I uploaded the list of contributors here: https://caltech-curation.textpressolab.com/files/priv/

**Comment by valearna** [comment]
We don't have a script to send out custom emails programmatically. We could write one but we would probably hit the gmail limits. Do you use a system to send out emails in bulk?

**Comment by azurebrd** [comment]
Thanks @valearna .  If possible, please make subdirectory for categories (like ACKnowledge), so that the top folder doesn't eventually get too long.  I do'nt know if [alzheimer_summaries/](https://caltech-curation.textpressolab.com/files/priv/alzheimer_summaries/)  and [document_classification_training_sets/](https://caltech-curation.textpressolab.com/files/priv/document_classification_training_sets/) belong under another umbrella folder

**Comment by valearna** [comment]
Thanks @azurebrd, I created a new subdir "acknowledge". The other dirs you mentioned are currently linked by other scripts but I'll clean them up soon.

**Comment by azurebrd** [comment]
Cool, thanks @valearna .  If the other directories are needed by scripts, it's fine to leave just those two there.  Thanks.

**Comment by draciti** [comment]
All contributors please!

**Comment by valearna** [comment]
@draciti the list I've uploaded has all contributors

**Comment by draciti** [comment]
Sorry Valerio, I did not refresh the page and I responded without seeing there were more messages. Apologies!

I will try to send out the message with the outreach account. If I encounter problems, I will let you all know.

**Comment by draciti** [comment]
Done, closing. Thanks, @valearna and @azurebrd !
